name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install llvm clang lld

      - name: Get Nexus AM
        run: git clone https://github.com/OpenXiangShan/nexus-am.git $HOME/nexus-am

      - name: Create /tmp/simuben.yml
        run: |
          ./test/simuben.sh
          cat /tmp/simuben.yml

      - name: Run BaSim
        run: |
          ./basim/main.py \
            --run-name test \
            --dir ./test \
            --simuben ./simuben/main.py \
            --config /tmp/simuben.yml

      - name: Print CSVs
        run: |
          echo "<| The baseline |>"
          cat ./test/baseline.csv
          echo "<| SimuBen |>"
          cat /tmp/basim/test/verilator.brief.merged.csv

      - name: Generate a report
        run: |
          ./bendiff/main.py \
            -o /tmp/basim/test/verilator.brief.merged.csv \
            -n /tmp/a.csv | ./diffvis/main.py > /tmp/a.html
          cat /tmp/a.html
