name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get LLVM Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install llvm clang lld

      - name: Get Nexus AM
        run: git clone https://github.com/OpenXiangShan/nexus-am.git $HOME/nexus-am

      - name: Get NEMU
        run: git clone https://github.com/OpenXiangShan/NEMU.git $HOME/NEMU

      - name: Get Verilator
        run: echo "It remains as an exercise"

      - name: Create /tmp/simuben.yml
        run: |
          ./test/simuben.sh
          cat /tmp/simuben.yml

      - name: Run SimuBen
        run: |
          ./basim/main.py \
            --run-name  test \
            --dir       ./test \
            --simuben   ./simuben/main.py \
            --config    /tmp/simuben.yml

      - name: Print SimuBen Verilator Report
        run: |
          echo "<| The baseline |>"
          cat ./test/baseline.csv
          echo "<| SimuBen |>"
          cat /tmp/basim/test/verilator.brief.merged.csv

      - name: Generate SimuBen HTML Report
        run: |
          ./bendiff/main.py \
            --old-path /tmp/a.csv \
            --new-path /tmp/basim/test/verilator.brief.merged.csv \
            | ./diffvis/main.py -o baseline -n test > /tmp/a.html
          cat /tmp/a.html
